### ISSUE TITLE
Colors in Sign Column

### ISSUE THREAD

**Issue by HiCodin** [KabbAmine/myVimFiles#1]
Hi, what plugin are you using to show the "yellow" color and "green" color on the sign column ?

**Comment by KabbAmine** [comment]
GitGutter with one unicode character, check the related configuration in `config/plugins.vim`.

**Comment by HiCodin** [comment]
ah i see. thanks for the response. will check out your configs. Pretty cool setup you have there. :)

**Comment by KabbAmine** [comment]
Thanks
